Repository EqualStreetNames/equalstreetnames, pull requests merged in 2021-05, with the labels that each got.

#175 ♻️ Refactor process using Symfony Console
  .github/workflows/process.yml
  process/Command/AbstractCommand.php
  process/Command/BoundaryCommand.php
  process/Command/GeoJSONCommand.php
  process/Command/OverpassCommand.php
  process/Command/StatisticsCommand.php
  process/Command/WikidataCommand.php
  process/Model/Config/Config.php
  process/Model/Config/ExcludeRelationWay.php
  process/Model/Config/GenderRelationWay.php
  process/Model/Details/Details.php
  process/Model/Details/LanguageValue.php
  process/Model/GeoJSON/Feature.php
  process/Model/GeoJSON/FeatureCollection.php
  process/Model/GeoJSON/Geometry/Geometry.php
  process/Model/GeoJSON/Geometry/LineString.php
  process/Model/GeoJSON/Geometry/MultiLineString.php
  process/Model/GeoJSON/Properties.php
  process/Model/Overpass/Element.php
  process/Model/Overpass/Node.php
  process/Model/Overpass/Overpass.php
  process/Model/Overpass/Relation.php
  process/Model/Overpass/Relation/Member.php
  process/Model/Overpass/Way.php
  process/Model/Wikidata/Claims.php
  process/Model/Wikidata/Entity.php
  process/Model/Wikidata/LanguageValue.php
  process/Wikidata/Wikidata.php
  process/composer.json
  process/composer.lock
  process/phpcs.xml.dist
  process/phpstan.neon
  process/process.php
  process/scripts/checks/relation-member.php
  process/scripts/geojson.php
  process/scripts/library/geojson/gender.php
  process/scripts/library/geojson/geometry.php
  process/scripts/library/geojson/openstreetmap.php
  process/scripts/library/geojson/wikidata.php
  process/scripts/library/statistics.php
  process/scripts/overpass-relation.php
  process/scripts/overpass-way.php
  process/scripts/statistics.php
  process/scripts/wikidata.php
Labels: enhancement

#189 Comment process source code and update documentation
  docs/README.md
  docs/scripts/README.md
  docs/scripts/statistics.md
  process/Command/AbstractCommand.php
  process/Command/BoundaryCommand.php
  process/Command/GeoJSONCommand.php
  process/Command/OverpassCommand.php
  process/Command/StatisticsCommand.php
  process/Command/WikidataCommand.php
  process/README.md
  process/docs/geojson.md
  process/docs/overpass.md
  process/docs/wikidata.md
Labels: documentation

#187 Get information from CSV file
  process/Command/AbstractCommand.php
  process/Command/GeoJSONCommand.php
  process/Command/StatisticsCommand.php
  process/Model/Details/Details.php
  process/phpstan.neon
  website/src/script/popup.ts
Labels: enhancement

#196 Create process metadata
  README.md
  global/build.js
  process/Command/StatisticsCommand.php
  website/build.js
  website/src/script/chart.ts
  website/src/script/index.ts
Labels: enhancement

#197 Report errors during build process
  global/build.js
  website/build.js
Labels: bug

#205 Fix chart and statistics display
  website/src/script/chart.ts
  website/src/script/colors.ts
Labels: enhancement

#201 Extract information for P138 ("named after") Wikidata property
  process/Command/GeoJSONCommand.php
  process/Command/WikidataCommand.php
  process/Model/Wikidata/Claims.php
  process/Wikidata/Wikidata.php
Labels: enhancement
